CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    DOCUMENT VARCHAR(11),
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DISCRETION VARCHAR(100),
    PRICE NUMERIC(20,2)
);

CREATE TABLE REQUEST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    DATE_REQUEST TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_REQUEST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    REQUEST_ID INTEGER REFERENCES REQUEST (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    QUANTITY INTEGER
);